services:
  mysql:
    image: mysql:8.0
    container_name: my_doggy_love_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Abc12345!
      MYSQL_DATABASE: my_doggy_love
      MYSQL_USER: appuser
      MYSQL_PASSWORD: AppPass123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]

volumes:
  db_data:


